name: agoy_weather
description: A new Flutter project.

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0" # Sesuaikan versi SDK Dart yang kamu gunakan

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3 # Tambahkan dependency http untuk API
  cupertino_icons: ^1.0.8
  intl: ^0.17.0 # Tambahkan dependency intl
  fl_chart: ^0.35.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/clear.jpg
    - assets/images/rain.jpg
    - assets/images/clouds.jpg
    - assets/images/snow.jpg
    - assets/images/thunderstorm.jpg
    - assets/fonts/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
